Remove redundant withRateLimit call from OpenAiChatModel.
spring-projects/spring-ai pull request #1207
Opened 2024-08-12 01:46 UTC by KAMO030

The withRateLimit call is redundant as rateLimit is already handled conditionally elsewhere. Its removal helps simplify the code and improves maintainability.

2024-08-15 20:07 UTC, sobychacko requested changes

2024-08-15 20:07 UTC, sobychacko commented on models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiChatModel.java
> +import org.springframework.ai.chat.observation.*;
Avoid import using *.

2024-08-15 20:07 UTC, sobychacko commented on models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiChatModel.java
> +import org.springframework.util.*;
Avoid import using *.

2024-08-15 20:07 UTC, sobychacko commented on models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiChatModel.java
> +import java.util.*;
No * import.

2024-08-16 15:56 UTC, markpollack commented
thanks!  merged in 3bef5c12bfdfadab6b49e8f5551baaa2d6c96208

2024-08-16 15:56 UTC, closed without merging