Add Spring Boot auto-configuration for Neo4j vector store
spring-projects/spring-ai pull request #191
Opened 2023-12-22 15:11 UTC by King-Chau

Add Spring Boot auto-configuration for Neo4j vector store

2023-12-22 15:13 UTC, King-Chau commented
@tzolov Please review, thank you.

2023-12-23 14:14 UTC, tzolov requested changes
Thanks @King-Chau 
It looks great! I have few minor recommendations about the code style and one important concern about exposing the  `org.neo4j.*` in the spring-ai API. 

Btw, your PR made me review the other vector stores and I've tried to clean the similar  issues [there](https://github.com/spring-projects/spring-ai/commit/472fadda615a169e2df2b37f1f5b45b15461ec65).

2023-12-23 16:10 UTC, King-Chau commented on spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/neo4j/Neo4jVectorStoreProperties.java
> +@ConfigurationProperties(CONFIG_PREFIX)
good point, will change

2023-12-23 16:11 UTC, King-Chau commented on spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/neo4j/Neo4jDriverProperties.java
> +public class Neo4jDriverProperties {
good point, will change

2023-12-23 16:20 UTC, King-Chau commented on spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/neo4j/Neo4jDriverProperties.java
> +import org.neo4j.driver.AuthToken;
Good point. I already removed org.neo4j API in Neo4jDriverProperties. 
The properties are the same as the existing neo4j spring boot autoconfig.

2023-12-24 07:42 UTC, tzolov commented
LGTM, thank you  @King-Chau

2023-12-24 08:14 UTC, tzolov commented
Rebased, squashed and merged at: b625ab1c1589dc6be0240b2d76d7023d43a71dcd

2023-12-24 08:14 UTC, closed without merging