Integration of Spring Cloud AWS to management AWS credentials and region configuration to use AWS Bedrock.
spring-projects/spring-ai pull request #590
Opened 2024-04-16 08:17 UTC by wmz7year

Integration of Spring Cloud AWS to support the following credentials configuration.

see: https://docs.awspring.io/spring-cloud-aws/docs/3.1.0/reference/html/index.html#credentials

And compatible with Spring Cloud AWS configuration and usage for AWS Bedrock.

2024-04-20 06:13 UTC, tzolov commented
Hi @wmz7year, thanks for taking a pick at this.

Before we start reviewing it i have to point that the `<artifactId>spring-cloud-aws-starter</artifactId>`  is not acceptable. 
In fact no boot starter in a library code is ok.  

So please cherry pick only the necessary minim of dependency.  Often the awspring starters will try to bring the entire AWS ecosystem into your project.

2024-04-20 09:40 UTC, wmz7year commented
Maybe there is another solution for the compatibility between Spring-AI and Spring-Cloud-AWS.

Sprint AI defined connection properties in `BedrockAwsConnectionConfiguration` and created `AwsCredentialsProvider` in `BedrockAwsConnectionConfiguration`.

But currently, we don't use `AwsRegionProvider` to manage the region configuration.




So maybe we can keep the current `BedrockAwsConnectionConfiguration` and the other BedrockClients's auto-configuration conditions; maybe only check 'AwsCredentialsProvider' and `AwsRegionProvider`, not dependency with `BedrockAwsConnectionProperties`.


So this will be compatible with Spring-Cloud-AWS and not necessarily integrated with it.

How do you think about this, if this is ok I'll change the PR @tzolov

2024-04-20 13:24 UTC, wmz7year commented
Hi @tzolov could you check this out again? I removed spring-cloud-aws dependency and provided new capabilities with custom `AwsCredentialsProvider` and `AwsRegionProvider` .

2024-04-21 10:01 UTC, tzolov requested changes
Thank you @wmz7year. It looks very good. 
Please fix the minor test naming issue and we are very close to merging it.

2024-04-21 10:11 UTC, wmz7year commented on spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/bedrock/BedrockAwsConnectionConfigurationT.java
> +public class BedrockAwsConnectionConfigurationT {
Done, my mistake xD

2024-04-22 06:51 UTC, tzolov approved these changes

2024-04-22 06:51 UTC, tzolov commented
Thank you @wmz7year , PR LGTM

2024-04-22 07:10 UTC, merged