Enhancing Elasticsearch vector store implementation
spring-projects/spring-ai pull request #592
Opened 2024-04-16 13:17 UTC by l-trotta

This PR provides a more performant search function for the Elasticsearch vector store and removes the bean autoconfiguration.

## In depth

### Autoconfiguration

The current implementation of `afterPropertiesSet()` automatically creates a new index with a set of properties that only works with OpenAI, or any other model that works with vectors with a dimension of 1536; users adopting other models would currently have to manually delete the index. By default, Elasticsearch automatically creates the correct index settings when it receives the first PUT request for vectors, so in our opinion there's no need for such autoconfiguration. 

### Search

The function used now is [script_score](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-script-score-query.html), which can be slow for large data samples since it does a brute force comparison with all vectors using the similarity function. This PR replaces it with the approximate [knn search](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html), more performant because it only scans the closest neighbours. The similarity functions available for `knn` can be easily configured in the index mapping by setting the correct name. 

##

We would also like to contribute to the documentation, should that be done in a different PR?  

Thank you @JM-Lab for the original implementation, would you like to review these changes?

 (Disclosure: I work for Elastic)

2024-04-17 15:38 UTC, JM-Lab commented
Hi @l-trotta,

Thanks for the update. I liked how script_score was quick to implement due to available examples, but I'm pleased we're switching to KNN for better performance.

Could you check if the code at https://github.com/spring-projects/spring-ai/blob/main/vector-stores/spring-ai-elasticsearch-store/src/main/java/org/springframework/ai/vectorstore/ElasticsearchAiSearchFilterExpressionConverter.java needs any improvements?

I'm looking forward to the official documentation for the Elasticsearch vector store of the Spring AI project, which I think @tzolov will address.

2024-04-30 07:02 UTC, tzolov commented
@l-trotta , thank you for the improvements. 
Could you please rebase and update your PR after the https://github.com/spring-projects/spring-ai/pull/633 merge.

2024-05-06 15:31 UTC, l-trotta commented
Updated! I'd like to explain why I removed the `dense-vector-indexing` property: quoting the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/dense-vector.html#dense-vector-params), 

> If true, you can search this field using the [kNN search API](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search-api.html). Defaults to true.

And since this implementation uses kNN search, setting this to false would make the data unsearchable.

2024-06-10 07:16 UTC, ezimuel commented
@tzolov what's the status of this PR? Thanks.

2024-06-16 08:51 UTC, tzolov commented
@l-trotta thanks for your contribution and thank you for your patience.

While reviewing the PR i've noticed that you have removed the capability to override the similarityFunction at runtime? 
Is there any particular reason to reduce this flexibility?  Either way it renders this [ElasticsearchVectorStoreAutoConfigurationIT](https://github.com/spring-projects/spring-ai/blob/879f99239410cd44515708e4ac6ab75456a0c812/spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/elasticsearch/ElasticsearchVectorStoreAutoConfigurationIT.java#L74) almost useless? 
If there are not strong reasons to have this immutable perhaps we should re-enable the `withSimilarityFunction`  setter?

2024-06-16 09:31 UTC, tzolov requested changes
Thanks @l-trotta , 
It looks good but there few things that needs clarification/fixing. Please check my comments. 
Looking forward for merging this improvement.

2024-06-16 09:31 UTC, tzolov commented on spring-ai-spring-boot-autoconfigure/pom.xml
> +		<dependency>
What is the reason to add the elasticsearch-java explicitly here? As it is already defined in the vector-store dependenies?

2024-06-16 09:31 UTC, tzolov commented on vector-stores/spring-ai-elasticsearch-store/src/main/java/org/springframework/ai/vectorstore/ElasticsearchVectorStore.java
> -	public ElasticsearchVectorStore withSimilarityFunction(String similarityFunction) {
Is it required to remove the ability to change the similarity function at runtime? 
This by the way breaks the `ElasticsearchVectorStoreAutoConfigurationIT` tests.

2024-06-17 09:53 UTC, l-trotta commented
@tzolov Thank you for the review, I'll explain my changes:

- Removal of the `withSimilarityFunction` setter: in elasticsearch the similarity function is defined as a mapping property of the index and cannot be changed, trying to update the property in the mapping will result in the following error: 
  ```
  {
    "error": {
      "root_cause": [
        {
          "type": "illegal_argument_exception",
          "reason": """Mapper for [embedding] conflicts with existing mapper:
	  Cannot update parameter [similarity] from [dot_product] to [cosine]"""
        }
      ],
      "type": "illegal_argument_exception",
      "reason": """Mapper for [embedding] conflicts with existing mapper:
	  Cannot update parameter [similarity] from [dot_product] to [cosine]"""
    },
    "status": 400
  }
  ```
  so the only way to change mapping is to create another index, and in this case a new vector store instance.
- Having `elasticsearch-java` explicitly defined in autoconfiguration: while testing the autoconfiguration I noticed it was importing an older version of the client  (8.10.4), which breaks the current implementation of the vector store since the knn query was recently fixed with version 8.13.3, so I wanted to make sure that this would be the version used, but maybe it's an issue with my local environment? If everything works without that it can be removed.

2024-06-17 13:05 UTC, tzolov commented
Thanks for the clarification @l-trotta !

It seems latest Spring Boot 3.3.x (the one we use for our auto-configs) is already at [Elasticsearch Client 8.13.4](https://github.com/spring-projects/spring-boot/blob/v3.3.0/spring-boot-project/spring-boot-dependencies/build.gradle). 
So I guess we are fine without the forced dependencies?  

Perhaps you can mention (in a separate PR) this requirement in the docs. E.g. if someone is using pre 3.3. Boot they have to add the elastic search `8.13.4` dependency to their poms?

2024-06-17 13:21 UTC, tzolov commented
rebased, squashed and merged at 78f3797f8d2c06cb429e6705f7b5eade6259dcf3

2024-06-17 13:21 UTC, closed without merging

2024-06-17 13:22 UTC, tzolov commented
@l-trotta thank you for the great work! 
Just merged the PR. 
Please check if the dependencies work as expected and consider adding a NOTE in the documentation as suggested above.

2024-06-17 13:32 UTC, l-trotta commented
@tzolov thank you! I'll test with an older boot version, if there could be version problems I'll open another PR for the documentation.

2024-08-07 10:11 UTC, ezimuel commented
@tzolov do you know when this PR will be public released? We would like to prepare some materials to promote this integration for Elasticsearch. Thanks!