Add Couchbase vector store support
spring-projects/spring-ai pull request #939
Opened 2024-06-23 17:29 UTC by ldoguin

- Implement CouchbaseVectorStore, including support for filter expression conversion.
- Add couchbase vectore store documentation
- Add spring boot autoconfig and starter

Resolves# https://github.com/spring-projects/spring-ai/issues/938

2024-06-24 09:26 UTC, tzolov commented
Thanks for the contribution @ldoguin 

Before we can start the review could please: 
 - add the couchbase.adoc to the [nav.adoc](https://github.com/spring-projects/spring-ai/blob/main/spring-ai-docs/src/main/antora/modules/ROOT/nav.adoc) catalog (they vector stores are listed in alphabetical order). 
 - add the vector store and the boot starter dependency to the [BOM's pom ](https://github.com/spring-projects/spring-ai/blob/main/spring-ai-bom/pom.xml)

2024-06-24 11:28 UTC, ldoguin commented
Hi @tzolov, just added them. Thank you !

2024-06-24 23:12 UTC, sobychacko requested changes

2024-06-24 23:14 UTC, sobychacko commented
@ldoguin, I added some more minor comments to the review. I also suggest you add some testing around the Boot auto-configuration. Take a look here for examples: https://github.com/spring-projects/spring-ai/tree/main/spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore.

2024-06-25 18:32 UTC, sobychacko requested changes

2024-06-25 18:32 UTC, sobychacko commented on vector-stores/spring-ai-couchbase-store/src/main/java/org/springframework/ai/vectorstore/CouchbaseVectorStore.java
> +		Thread.sleep(100);
Why do we need to `sleep` here? Can we avoid that and use a more deterministic mechanism? There might be a scenario in which the code we want to execute fully may not be ready with the sleep.

2024-06-25 18:32 UTC, sobychacko commented on vector-stores/spring-ai-couchbase-store/src/main/java/org/springframework/ai/vectorstore/CouchbaseVectorStore.java
> +		Thread.sleep(100);
same comment as above.

2024-06-25 18:32 UTC, sobychacko commented on vector-stores/spring-ai-couchbase-store/src/main/java/org/springframework/ai/vectorstore/CouchbaseVectorStore.java
> +		Thread.sleep(100);
same comment as above.

2024-06-27 15:40 UTC, ldoguin commented
@sobychacko change the Thread.sleep to watcher and retries. Unfortunately we don't have a synchronous API for these.

2024-06-27 20:32 UTC, sobychacko commented
@ldoguin Thanks for the updates. When running the tests locally, I see the following two tests consistently fail. Could you look into them?

`CouchbaseVectorStoreAutoConfigurationIT#addAndSearchWithFilters`
`CouchabaseVectorStoreIT#searchWithFilters`

Also, can you rebase the PR branch against the latest main?

2024-07-01 10:24 UTC, ldoguin commented
Hi @sobychacko, I sadly can't reproduce. Is it a Couchbase connection error ?

2024-07-01 14:52 UTC, sobychacko commented
@ldoguin These are the types of errors I am seeing locally:

```
Caused by: com.couchbase.client.core.error.UnambiguousTimeoutException: WaitUntilReady timed out in stage WAIT_FOR_CONFIG (spent PT1.001939792S in that stage) {"bucket":"example","checkedServices":
[],"desiredState":"ONLINE","remainingPingTargets":{},"services":{"mgmt":[{"last_activity_us":1006741,"state":"connected","circuit_breaker_state":"disabled","id":"0x9367b2dd",
"remote":"localhost:53016","local":"127.0.0.1:53070"},{"lastConnectAttemptFailure":"finishConnect(..) failed: Connection refused: localhost/127.0.0.1:8091 - Check server ports and cluster encryption setting.","state":"disconnected","circuit_breaker_state":"disabled"},
{"lastConnectAttemptFailure":"finishConnect(..) failed: Connection refused: localhost/127.0.0.1:8091 - Check server ports and cluster encryption setting.","state":"disconnected","circuit_breaker_state":"disabled"},{"lastConnectAttemptFailure":"finishConnect(..) failed: Connection refused: localhost/127.0.0.1:8091 - Check server ports and cluster encryption setting.","state":"disconnected","circuit_breaker_state":"disabled"},
{"lastConnectAttemptFailure":"finishConnect(..) failed: Connection refused: localhost/127.0.0.1:8091 - Check server ports and cluster encryption setting.","state":"disconnected","circuit_breaker_state":"disabled"},{"lastConnectAttemptFailure":"finishConnect(..) failed: Connection refused: localhost/127.0.0.1:8091 - Check server ports and cluster encryption setting.","state":"disconnected","circuit_breaker_state":"disabled"},{"lastConnectAttemptFailure":"finishConnect(..) 
```

2024-07-01 15:41 UTC, ldoguin commented
@sobychacko So it does look like a couchbase/testcontainer issues. Let me see how we are doing tests with Spring Data Couchabse.

2024-07-26 15:46 UTC, sobychacko commented
@ldoguin Any updates on this PR?

2024-11-25 21:43 UTC, markpollack commented
Hi @ldoguin Its' beena while, wondering if you could take a look again on this.

2025-02-18 11:29 UTC, deniswsrosa commented
@markpollack Sorry for the delay, we will start working on it this week and push all the fixes.

2025-03-25 18:21 UTC, sobychacko commented
This issue has now been resolved via https://github.com/spring-projects/spring-ai/commit/d25d37ab12c0fd4eb77773d157eb15002b4ff897.

2025-03-25 18:21 UTC, closed without merging